import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/**
 * @author Astafyev Igor
 *         11-405
 *         for SemWork
 */

public class CreateTable {
    public static void main(String[] args) {
        try {
            createTableSubject();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static Connection getConnection() throws IOException, ClassNotFoundException, SQLException {
        Properties props = new Properties();
        props.load(new FileInputStream("etc/properties/connection.properties"));
        String driver = props.getProperty("driver");
        String url = props.getProperty("url");
        String user = props.getProperty("user");
        String pass = props.getProperty("pass");
        Class.forName(driver);
        return DriverManager.getConnection(url, user, pass);
}

    private static void createTableSubject() throws SQLException, ClassNotFoundException, IOException {
        Connection connection = null;
        try {
            connection = getConnection();
            Statement statement = connection.createStatement();
            statement.executeUpdate("create table if not exists USERS (id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) " +
                    "NOT NULL PRIMARY KEY, name varchar)");
        } finally {
            if (connection != null) {
                connection.close();
            }
        }
    }
}
