import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Properties;

/**
 * @author Astafyev Igor
 *         11-405
 *         for SemWork
 */

public class TestConnection {

    public static void main(String[] args) {
        try {
            testConnection();

            testSelect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void testConnection() throws SQLException, ClassNotFoundException, IOException {
        Connection connection = null;
        try {
            connection = getConnection();
        } finally {
            if (connection != null) {
                connection.close();
            }
        }
    }

    private static Connection getConnection() throws IOException, ClassNotFoundException, SQLException {
        Properties props = new Properties();
        props.load(new FileInputStream("etc/properties/connection.properties"));
        String driver = props.getProperty("driver");
        String url = props.getProperty("url");
        String user = props.getProperty("user");
        String pass = props.getProperty("pass");
        Class.forName(driver);
        return DriverManager.getConnection(url, user, pass);
    }

    private static void testCreate() throws SQLException, ClassNotFoundException, IOException {
        Connection connection = null;
        try {
            connection = getConnection();
            Statement statement = connection.createStatement();
            statement.executeUpdate("create table USERS (id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) " +
                    "NOT NULL PRIMARY KEY, name varchar)");
        } finally {
            if (connection != null) {
                connection.close();
            }
        }
    }

    private static void testSelect() throws ClassNotFoundException, IOException, SQLException {
        Connection connection = null;
        try {
            connection = getConnection();
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from USERS");
            while (resultSet.next()) {
                long id = resultSet.getLong("id");
                String name = resultSet.getString("name");
                System.out.println("id=" + id + " name=" + name);
            }
        } finally {
            if (connection != null) {
                connection.close();
            }
        }
    }
}
